---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(pheatmap)
```

```{r}
shared <- read_tsv("~/Documents/MPRA/Cancer_MPRA_Scaleup/MakingFigures/SharedeGeneNetwork/enrichment.Process_sharedhconvert_vsuniverse_GOBP.txt")
shared <- shared[order(shared$`false discovery rate`),]
shared <- shared %>% mutate(Term=factor(`term description`, levels=`term description`))
```

```{r}
ggplot(shared, aes(x = Term, y = `false discovery rate` )) +
  geom_col()

```
Pathways to keep
```{r}
keep <- c("response to interferon-gamma", "antigen processing and presentation of
  exogenous peptide antigen", "DNA packaging", "innate immune response",
  "immune response","cytokine-mediated signaling pathway",
  "protein heterotetramerization", "cellular component assembly",
  "antigen processing and presentation of endogenous peptide antigen",
  "negative regulation of natural killer cell mediated cytotoxicity",
  "regulation of gene silencing by miRNA",
  "cellular response to cytokine stimulus",
  "response to stress",
  "positive regulation of apoptotic cell clearance",
  "chromatin organization", "organelle organization",
  "regulation of T cell mediated immunity","canonical Wnt signaling pathway",
  "adaptive immune response", "regulation of actin polymerization or depolymerization",
  "regulation of corticosterone secretion",
  "regulation of mitotic cell cycle",
  "nuclear division")
shared_filt <- dplyr::filter(shared, Term %in% keep)
```

```{r}
termplot <- ggplot(shared_filt, aes(x = Term, y = -log10(`false discovery rate` ))) +
  geom_col() + coord_flip() + theme_classic() + 
  ylab("-log10(FDR)") + xlab("GO Biological Process")
termplot
ggsave("~/Documents/MPRA/Cancer_MPRA_Scaleup/MakingFigures/SharedeGeneNetwork/alternate_pathway_vis.pdf", 
       device="pdf", plot = termplot, width = 5.5, height = 4, unit = "in", dpi="print")
```


```{r}
res_merge <- read_tsv("~/Documents/MPRA/Cancer_MPRA_Scaleup/Analysis11.12.20/Analysis11.27.20/res_merge_withhitannot_031021.tsv")
egene_mat <- res_merge  %>% filter(!is.na(hit_spec)) %>%
  dplyr::select(hit_spec, eqtlgen_egenes, gtex_egenes_spec, hichip_egene,
                genes_within_10kb)
egene_mat <- pivot_longer(egene_mat, cols = c(eqtlgen_egenes, gtex_egenes_spec,
                                              hichip_egene,genes_within_10kb),
                names_to = "source",
                          values_to = "egene")
egene_mat <- egene_mat %>% mutate(egene = str_split(egene, ",|;")) %>%
  unnest(cols = c(egene))
egene_mat <- egene_mat %>% mutate(hit_spec = str_split(hit_spec, ",")) %>%
  unnest(cols = c(hit_spec))
egene_mat <- dplyr::filter(egene_mat, !is.na(egene))
egene_mat <- egene_mat %>% group_by(egene) %>% 
  summarise(source = ifelse(length(unique(source)) > 1, "multiple",source ),
            hit_spec = paste(unique(sort(hit_spec)), collapse=","))
egene_mat <- egene_mat %>% mutate(hit_spec_2 = hit_spec)

egene_mat <- egene_mat %>% mutate(hit_spec = str_split(hit_spec, ",")) %>%
  unnest(cols = c(hit_spec))
# egene_mat <- egene_mat %>% mutate(yes_or_no = 1)
# egene_mat <- pivot_wider(egene_mat, names_from = hit_spec, values_from=yes_or_no )
egene_mat <- pivot_wider(egene_mat, names_from = hit_spec, values_from=source )
egene_mat[is.na(egene_mat)] <- "NA"
```

```{r}
#recreate a data set

egene_mat <- egene_mat[order(egene_mat$hit_spec_2),]
egene_mat <- egene_mat %>% mutate(egene=factor(egene, levels=egene))
library(reshape2)
dat3 <- melt(dplyr::select(egene_mat, -hit_spec_2), id.var = "egene")

ggplot(dat3, aes(variable, egene)) + geom_tile(aes(fill = value),
   colour = "white") + scale_fill_manual(values=c("red", "blue", "black", "green",
                                                  "yellow", "white", "purple"))
```

Not working well, going back to pheatmap
```{r fig.width=9, fig.height=4}
res_merge <- read_tsv("~/Documents/MPRA/Cancer_MPRA_Scaleup/Analysis11.12.20/Analysis11.27.20/res_merge_withhitannot_031021.tsv")
egene_mat <- res_merge  %>% filter(!is.na(hit_spec)) %>%
  dplyr::select(hit_spec, eqtlgen_egenes, gtex_egenes_spec, hichip_egene,
                genes_within_10kb)
egene_mat <- pivot_longer(egene_mat, cols = c(eqtlgen_egenes, gtex_egenes_spec,
                                              hichip_egene,genes_within_10kb),
                names_to = "source",
                          values_to = "egene")
egene_mat <- egene_mat %>% mutate(egene = str_split(egene, ",|;")) %>%
  unnest(cols = c(egene))
egene_mat <- egene_mat %>% mutate(hit_spec = str_split(hit_spec, ",")) %>%
  unnest(cols = c(hit_spec))
egene_mat <- dplyr::filter(egene_mat, !is.na(egene))
egene_mat <- egene_mat %>% group_by(egene) %>% 
  summarise(source = ifelse(length(unique(source)) > 1, "multiple",source ),
            hit_spec = paste(unique(sort(hit_spec)), collapse=","))
egene_mat <- egene_mat %>% mutate(hit_spec_2 = hit_spec)

egene_mat <- egene_mat %>% mutate(hit_spec = str_split(hit_spec, ",")) %>%
  unnest(cols = c(hit_spec))
 egene_mat <- egene_mat %>% mutate(yes_or_no = 1)
 egene_mat <- pivot_wider(egene_mat, names_from = hit_spec, values_from=yes_or_no )
egene_mat[is.na(egene_mat)] <- 0
egene_mat_t <- egene_mat[4:17]
rownames(egene_mat_t) <- egene_mat$egene
source_annot <- data.frame(source = egene_mat$source)
rownames(source_annot) <- egene_mat$egene
pheatmap(t(egene_mat_t), treeheight_row=0, treeheight_col=0,
         annotation_col = source_annot, fontsize_col=2,
         fontsize_row=30)
```
Now trying with just shared egenes
```{r fig.width = 5, fig.height = 3}
res_merge <- read_tsv("~/Documents/MPRA/Cancer_MPRA_Scaleup/Analysis11.12.20/Analysis11.27.20/res_merge_withhitannot_031021.tsv")
egene_mat <- res_merge  %>% filter(!is.na(hit_spec)) %>%
  dplyr::select(hit_spec, eqtlgen_egenes, gtex_egenes_spec, hichip_egene,
                genes_within_10kb)
egene_mat <- pivot_longer(egene_mat, cols = c(eqtlgen_egenes, gtex_egenes_spec,
                                              hichip_egene,genes_within_10kb),
                names_to = "source",
                          values_to = "egene")
egene_mat <- egene_mat %>% mutate(egene = str_split(egene, ",|;")) %>%
  unnest(cols = c(egene))
egene_mat <- egene_mat %>% mutate(hit_spec = str_split(hit_spec, ",")) %>%
  unnest(cols = c(hit_spec))
egene_mat <- dplyr::filter(egene_mat, !is.na(egene))
egene_mat <- egene_mat %>% group_by(egene) %>% 
  summarise(source = ifelse(length(unique(source)) > 1, "multiple",source ),
            hit_spec = paste(unique(sort(hit_spec)), collapse=","))
egene_mat <- egene_mat %>% mutate(hit_spec_2 = hit_spec)
egene_mat <- dplyr::filter(egene_mat, grepl(",", hit_spec_2))
egene_mat <- egene_mat %>% mutate(hit_spec = str_split(hit_spec, ",")) %>%
  unnest(cols = c(hit_spec))
 egene_mat <- egene_mat %>% mutate(yes_or_no = 1)
 egene_mat <- pivot_wider(egene_mat, names_from = hit_spec, values_from=yes_or_no )
egene_mat[is.na(egene_mat)] <- 0
egene_mat_t <- egene_mat[4:16]
rownames(egene_mat_t) <- egene_mat$egene
source_annot <- data.frame(source = egene_mat$source)
rownames(source_annot) <- egene_mat$egene

myColor = c("white", "black")
library(viridis)
library(ggsci)
library("scales")

plasma(5)
ggsci
ann_colors = list(`source` = c("eqtlgen_egenes" = "#91D1C299",
               "genes_within_10kb" = "#DC000099" ,
              "gtex_egenes_spec" = "#4DBBD599",
              "hichip_egene" = "#F39B7F99",
              "multiple" = "#8491B499"))
mypal <- pal_npg("nrc", alpha = 0.6)(16)
show_col(mypal)  
pheatmap(t(egene_mat_t), treeheight_row=0, treeheight_col=0,
         annotation_col = source_annot, fontsize_col=3,
         fontsize_row=20)
pheatmap(egene_mat_t, color=myColor, treeheight_row=0, treeheight_col=0,
         annotation_row = source_annot, fontsize_row=3,
         fontsize_col=10, annotation_colors= ann_colors,show_rownames=F,
         filename= c("~/Documents/MPRA/Cancer_MPRA_Scaleup/MakingFigures/SharedeGeneNetwork/alternate_common_gene_vis.pdf"), width =4, height = 4)

```

