---
title: "Find GTEx eGenes"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(readr)
library(tidyverse)
library(biomaRt)
library(here)
```


Getting GTEx eGenes for MPRA library SNPs
Using GTEx v8
From https://gtexportal.org/home/datasets, use GTEx_Analysis_v8_eQTL.tar

```{r}
lib <- read_tsv(here("output/lib_studies_idmerge_diseasesexpanded_coords3738_gtexIDuncollapsed_1.9.20.tsv"))
```
Find all the significant SNP-egene pairs in our tissues from gtex v8
```{r}
file_list <- list.files(path=here("data/LK_GTEx_Analysis_v8_eQTL/"),
                        pattern = ".*signif_variant_gene_pairs.txt$", full.names=T)
files_filt <- file_list[grepl("Brain|Colon|EBV|Esop|Thyroid|Skin|Pancreas|Breast|Lung|Uterus|Kidney|Ovary|Prostate", file_list)]
variant_ids <- unique(lib$variant_id)
egene_pairs <- data.frame()
for (file_name in files_filt){
  tissue = str_remove(str_remove(file_name, "\\.v8.*$"), "^.*\\/")
  df = read_tsv(file_name)
  df_rel = filter(df, variant_id %in% variant_ids)
  df_rel$tissue <- tissue
  egene_pairs <- rbind(egene_pairs, df_rel)
}

write_tsv(egene_pairs, here("output/significant_egene_pairs_for_snps_in_gtex_tissue_filtered_1.13.20.txt"))

```
Check into the misfit variant ids
```{r}
problem_ids <- unique(egene_pairs$variant_id[!(egene_pairs$variant_id %in% lib$variant_id)])
# none

```

#### Convert to HGNC symbol
```{r}
# convert to hgnc symbol

# settings
features=c('ensembl_gene_id','ensembl_transcript_id','entrezgene_id','hgnc_symbol', 'external_gene_name','refseq_mrna')
host='www.ensembl.org'
# human
hmart=useMart('ENSEMBL_MART_ENSEMBL', dataset='hsapiens_gene_ensembl',host=host)
results=getBM(attributes=features,mart=hmart)

# or skip to:
# results = read_tsv('~/Documents/MPRA/Cancer_MPRA/Lx_Analysis/geneID_mapping_human.tsv')

egene_med <- egene_pairs %>% mutate(gene_id = str_remove(gene_id, "\\.[0-9]+"))
key = dplyr::select(results, ensembl_gene_id, hgnc_symbol) %>% dplyr::filter(ensembl_gene_id %in% egene_med$gene_id) %>%
  distinct()

egene_med <- egene_med %>% rowwise() %>% 
  mutate(hgnc = ifelse(gene_id %in% key$ensembl_gene_id, key$hgnc_symbol[key$ensembl_gene_id == gene_id],
                       NA))
                                
                              
```

Write out the large df, then collapse it down to something I can put next to results df
```{r}
lib <- dplyr::rename(lib, Disease_expanded = disease_expanded)

# want to add tissue specific egenes
lib_gtex <- left_join(dplyr::select(lib, Causal_SNP, Ref,Alt, Disease_expanded, variant_id), 
                      dplyr::select(egene_med, variant_id, gene_id, tissue, hgnc, slope),
                      by=c("variant_id"="variant_id"))
# aligning the names used
gtex_tissue_filtered <- lib_gtex %>% rowwise() %>%
  mutate(correct_tissue = case_when(
    grepl("lung", Disease_expanded) & grepl("Lung", tissue) ~ T,
    grepl("brca", Disease_expanded) & grepl("Breast", tissue) ~ T,
    grepl("lymphoma", Disease_expanded) & grepl("EBV", tissue) ~ T,
    grepl("prad", Disease_expanded) & grepl("Prostate", tissue) ~ T,
    grepl("skin", Disease_expanded) & grepl("Skin", tissue) ~ T,
    grepl("ovca", Disease_expanded) & grepl("Ovary", tissue) ~ T,
    grepl("colon", Disease_expanded) & grepl("Colon", tissue) ~ T,
    grepl("paad", Disease_expanded) & grepl("Pancreas", tissue) ~ T,
    grepl("kidney", Disease_expanded) & grepl("Kidney", tissue) ~ T,
    grepl("thyroid", Disease_expanded) & grepl("Thyroid", tissue) ~ T,
    grepl("melanoma", Disease_expanded) & grepl("Skin", tissue) ~ T,
    grepl("esophagus", Disease_expanded) & grepl("Esopha", tissue) ~ T,
    grepl("brain", Disease_expanded) & grepl("Brain", tissue) ~ T,
    grepl("endometrial", Disease_expanded) & grepl("Uterus", tissue) ~ T,
    grepl("skin", Disease_expanded) & grepl("Skin", tissue) ~ T,
    T ~ F))
  
gtex_tissue_annot <- gtex_tissue_filtered %>%
  mutate(gtex_egenes_correct_tissue = ifelse(correct_tissue == T, hgnc, NA))

gtex_tissue_coll <- gtex_tissue_annot %>% group_by(variant_id) %>%
  summarise(gtex_egenes = paste("", unique(hgnc[!is.na(hgnc)]), sep="", collapse=","),
            gtex_egenes_ens = paste("", unique(gene_id[!is.na(hgnc)]), sep="", collapse=","),
            gtex_egenes_correct_tissue = 
              paste("", unique(gtex_egenes_correct_tissue[!is.na(gtex_egenes_correct_tissue)]),sep="", collapse=","),
            gtex_tissues = paste("", unique(tissue[!is.na(tissue)]), sep="", collapse=","),
            gtex_direction = paste("", unique(slope[!is.na(slope)]), sep="", collapse=","))

lib_gtex_merge <- left_join(lib, gtex_tissue_coll, by=c("variant_id"="variant_id"))

write_tsv(lib_gtex_merge, here("output/lib_studies_idmerge_diseasesexpanded_coords3738_GTExeGenes_tissuecolumn_1.13.20.tsv"))

```
