---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(clusterProfiler)
library(DOSE)
library(enrichR)
library(ReactomePA)
library(enrichplot)
library(org.Hs.eg.db)

```

```{r}
setEnrichrSite("Enrichr") # Human genes
dbs <- listEnrichrDbs()
```

```{r}
shared_egenes <- read_tsv("~/Documents/MPRA/Cancer_MPRA_Scaleup/MakingFigures/PathwayEnrichmentResults/SharedeGenes/shared_egenes_hconvert_list.txt", col_names = c("gene"))
enriched <- enrichr(shared_egenes$gene, databases=c("BioCarta_2013", "Reactome_2016",
                                                    "WikiPathways_2019_Human",
                                                    "Disease_Signatures_from_GEO_up_2014",
                                                    "KEGG_2019_Human",
                                                    "GO_Molecular_Function_2018",
                                                    "GeneSigDB",
                                                    "GO_Biological_Process_2018",
                                                    "Human_Phenotype_Ontology",
                                                    "OMIM_Disease",
                                                    "OMIM_Expanded",
                                                    "MSigDB_Oncogenic_Signatures",
                                                    "Cancer_Cell_Line_Encyclopedia",
                                                    "NCI-60_Cancer_Cell_Lines",
                                                    "Achilles_fitness_increase",
                                                    "Achilles_fitness_decrease",
                                                    "DisGeNET",
                                                    "ClinVar_2019"))
names(enriched)
enriched[["GO_Biological_Process_2018"]]
plotEnrich(enriched[["GO_Biological_Process_2018"]],
           numChar=100, y="Count", orderBy="P.value",
           title="")
```

```{r}
all_egenes <- read_tsv("~/Documents/MPRA/Cancer_MPRA_Scaleup/CytoscapeMaps/sharedegenes/all_egenes_reflist.txt", col_names="gene")
library(clusterProfiler)
library(org.Hs.eg.db)
all_egenes_entrez <- bitr(all_egenes$gene, fromType= "SYMBOL", toType="ENTREZID", OrgDb = org.Hs.eg.db)
shared_egenes_entrez <- bitr(shared_egenes$gene, fromType= "SYMBOL", toType="ENTREZID", OrgDb = org.Hs.eg.db)
ego <- enrichGO(gene          = shared_egenes$gene,
                universe      = all_egenes$gene,
                OrgDb         = org.Hs.eg.db,
                keyType = "SYMBOL",
                ont           = "BP",
                pAdjustMethod = "BH",
                pvalueCutoff  = 0.01,
                qvalueCutoff  = 0.05,
        readable      = TRUE)
ego1 <- enrichGO(gene          = all_egenes_entrez$ENTREZID,
                OrgDb         = org.Hs.eg.db,
                keyType = "ENTREZID",
                ont           = "BP",
                pAdjustMethod = "BH",
                pvalueCutoff  = 0.01,
                qvalueCutoff  = 0.05,
        readable      = TRUE)
ego2 <- enrichGO(gene          = shared_egenes_entrez$ENTREZID,
              universe = all_egenes_entrez$ENTREZID,
                OrgDb         = org.Hs.eg.db,
                keyType = "ENTREZID",
                ont           = "BP",
                pAdjustMethod = "BH",
                pvalueCutoff  = 0.01,
                qvalueCutoff  = 0.05,
        readable      = TRUE)

```

```{r fig.height = 0.75, fig.width = 3}

barplot(ego1)
barplot(ego2)

ego3 <- simplify(ego2, cutoff=0.7, by="p.adjust", select_fun=min)
dotplot(ego3)
goplot(ego2)
barplot(ego3, font.size=6)
?enrichplot::barplot

pdf(file="~/Documents/MPRA/Cancer_MPRA_Scaleup/MakingFigures/PathwayEnrichmentResults/goenrichment_sharedegenes_bgallegenes.pdf",width=6, height=2)
barplot(ego3, font.size=6)
dev.off()

# make a bar plot of the p-values, with the bars thinner
ego3_df <- data.frame(terms = ego3@result[["Description"]],
                      pvals = ego3@result[["p.adjust"]],
                      gene_num = ego3@result[["Count"]])
ego3_df$reformatted <- c("interferon-gamma-mediated\n signaling pathway","junk",
                         "antigen processing and presentation\nof exogenous antigen")
ggplot(ego3_df[c(1,3),], aes(x=pvals, y = reformatted)) + geom_col() + 
  theme_classic() + xlab("Adjusted p-value")+
  theme(axis.text.y = element_text(size = 9))
ggsave("~/Documents/MPRA/Cancer_MPRA_Scaleup/MakingFigures/PathwayEnrichmentResults/enrichedsharedvsallegenes_pvalplot.png", width=5.5, height = 1.25)
```

```{r}
res_merge <- read_tsv("~/Documents/MPRA/Cancer_MPRA_Scaleup/Analysis11.12.20/Analysis11.27.20/res_merge_withhitannot_031021.tsv")
egenes <- dplyr::select(res_merge, eqtlgen_egenes, gtex_egenes_spec, 
                        hichip_egene, genes_within_10kb, hit_spec) %>%
  mutate(eqtlgen_egenes = str_split(eqtlgen_egenes, ",|;"),
         gtex_egenes_spec = str_split(gtex_egenes_spec, ",|;"),
         hichip_egene = str_split(hichip_egene, ",|;"),
         genes_within_10kb = str_split(genes_within_10kb, ",|;")) %>%
  unnest(eqtlgen_egenes) %>% unnest(gtex_egenes_spec) %>%
  unnest(hichip_egene) %>% unnest(genes_within_10kb)
egenes <- egenes %>% pivot_longer(cols = c(eqtlgen_egenes, gtex_egenes_spec,
                                           hichip_egene, genes_within_10kb),
                                  names_to = "egene_type",
                                  values_to = "gene")
egenes <- dplyr::select(egenes, - egene_type) %>% distinct()
library(org.Hs.eg.db)
egenes_entrez <- bitr(egenes$gene, fromType= "SYMBOL", toType="ENTREZID", OrgDb = org.Hs.eg.db)
egenes <- right_join(egenes, egenes_entrez, by=c("gene" ="SYMBOL"))
```

Try comparecluster with all of the different sets

```{r width= 15}
  hmec_egenes = egenes$gene[grepl("hmec", egenes$hit_spec)]
egene_lists <- list(
  airway = egenes$ENTREZID[grepl("airway", egenes$hit_spec)],
  ast = egenes$ENTREZID[grepl("ast", egenes$hit_spec)],
  colon = egenes$ENTREZID[grepl("colon", egenes$hit_spec)],
  endo = egenes$ENTREZID[grepl("endo", egenes$hit_spec)],
  eso = egenes$ENTREZID[grepl("eso", egenes$hit_spec)],
  gm = egenes$ENTREZID[grepl("gm", egenes$hit_spec)],
  hmec = egenes$ENTREZID[grepl("hmec", egenes$hit_spec)],
  kc = egenes$ENTREZID[grepl("kc", egenes$hit_spec)],
  mc = egenes$ENTREZID[grepl("mc", egenes$hit_spec)],
  ov = egenes$ENTREZID[grepl("ov", egenes$hit_spec)],
  panc = egenes$ENTREZID[grepl("panc", egenes$hit_spec)],
  pros = egenes$ENTREZID[grepl("pros", egenes$hit_spec)],
  renal = egenes$ENTREZID[grepl("renal", egenes$hit_spec)],
  thy = egenes$ENTREZID[grepl("thy", egenes$hit_spec)]
)
comparing <- compareCluster(egene_lists, fun="enrichGO", ont="BP", OrgDb = org.Hs.eg.db)
comparingDO <- compareCluster(egene_lists, fun="enrichDO", ont="DO")
comparing_pathway2 <- compareCluster(geneClusters = egene_lists, fun="enrichPathway")
comparing_pathway <- compareCluster(geneClusters = egene_lists, fun="enrichPathway",
                                  universe=egenes$ENTREZID)


dotplot(comparing, font.size=6)
dotplot(comparingDO)
dotplot(comparing_pathway, font.size=4)
dotplot(comparing_pathway2, font.size=4)
pdf(file="~/Documents/MPRA/Cancer_MPRA_Scaleup/MakingFigures/PathwayEnrichmentResults/comparingclusters_bguniverse.pdf",width=6, height=3)
dotplot(comparing_pathway2, font.size=5, )
dev.off()
brca_enriched_go <- enrichGO(egene_lists$hmec, OrgDb = org.Hs.eg.db,
                             ont="BP")
brca_enriched_reactome <- enrichPathway(egene_lists$hmec,
                           universe=egenes$ENTREZID)
barplot(brca_enriched_reactome, font.size=5)
```
Trying to do selective pathways out of comparing
```{r}
head(comparing)
Description %in% c("cell junction organization", "apoptotic cell clearance" ,
                   "regulation of actin polymerization or depolymerization" ,
                   "regulation of G1/S transition of mitotic cell cycle",
                   "regulation of immune effector process")
```


```{r}
barplot(brca_enriched_reactome, font.size=5)

brca_egenes <- read_tsv("~/Documents/MPRA/Cancer_MPRA_Scaleup/CytoscapeMaps/brca/hit_egenes_brca_120920.txt")

```
```{r}
enriched_brca_rctm <- enrichr(brca_egenes$gene, databases=c( "Reactome_2016"))
names(enriched_brca_rctm)
enriched_brca_rctm[["Reactome_2016"]]
plotEnrich(enriched_brca_rctm[["Reactome_2016"]],
           numChar=100, y="Count", orderBy="P.value",
           title="")
cat(hmec_egenes, sep="\n")
```

