---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

```{r}
filenames <- list.files("~/Documents/MPRA/Cancer_MPRA_Scaleup/MakingFigures/Mutated-HCS-genetable/MutatedGenes_fromYang/", full.names = T)

```

```{r}
gene_df = c()
for (file in filenames){
  gene_list <- read_tsv(file)
  print(file)
  gene_list$celltype <- str_remove(str_remove(file, "^.*sig-"), "_.*$")
  gene_df <- rbind(gene_df, gene_list)
}
 gene_df <- gene_df %>% mutate(celltype = case_when(
  celltype == "BRCA" ~ "hmec",
  celltype == "Brain" ~ "ast",
  celltype == "Esophageal" ~ "eso",
  celltype == "KIRC" ~ "renal",
  celltype == "KIRP" ~ "renal",
  celltype == "LUAD" ~ "airway",
  celltype == "LUSC" ~ "airway",
  celltype == "Lymphoma" ~ "gm",
  celltype == "Melanoma" ~ "mc",
  celltype == "Prostate" ~ "pros",
  celltype == "Thyroid" ~ "thy",
  celltype == "Uterine" ~ "endo",
  T ~ celltype
))
# Missing: colon,skin,panc,ov
```

```{r}
res_merge <- read_tsv("~/Documents/MPRA/Cancer_MPRA_Scaleup/Analysis11.12.20/Analysis11.27.20/res_merge_withhitannot_031021.tsv")
```

Make a table of genes from the mutated list
```{r}
res_filt <- dplyr::filter(res_merge, !is.na(hit_spec))
yesorno <- apply(gene_df, 1, function(x) 
  res_filt$Causal_SNP[(grepl(x[["Gene"]], res_filt$hichip_egene) |
                          grepl(x[["Gene"]], res_filt$eqtlgen_egenes) |
                          grepl(x[["Gene"]], res_filt$genes_within_10kb) |
                          grepl(x[["Gene"]], res_filt$gtex_egenes_spec)) &
                         grepl(x[["celltype"]], res_filt$hit_spec)])
yesorno <- lapply(yesorno, function(x) paste(x, collapse=","))
yesorno <- lapply(yesorno, function(x) ifelse(x == "", NA, x))
yesorno_df <- data.frame(gene = gene_df$Gene, celltype = gene_df$celltype,
                         snps = unlist(yesorno))
yesorno_df <- yesorno_df %>% mutate(snps = str_split(snps, ",")) %>%
  unnest(snps)
# the grep backfired, remove RB1 and TP53 manually
yesorno_df <- dplyr::filter(yesorno_df, !gene %in% c("RB1","TP53", "TNR"))
yesorno_df <- dplyr::filter(yesorno_df, !is.na(snps))

```
There are genes that aren't in the data set 
TBL1XR1,ACTL6B, SF3B1, ZP4
Ask for full files

```{r}
hcs <- read_tsv("~/Documents/MPRA/Cancer_MPRA_Scaleup/CodingSNPs/HereditaryCancerSyndromes2.txt")
hcs <- hcs %>% mutate(Cancer = str_split(Cancer, ",")) %>%
  unnest(Cancer)
 hcs <- dplyr::select(hcs, Cancer, Gene)
# hcs$source <- "hereditary_cancer_syndrome"

```




```{r}
egenes <- res_merge %>% dplyr::select( disease, hit_spec, eqtlgen_egenes, gtex_egenes_spec,hichip_egene,
                                       genes_within_10kb)
egenes <- egenes %>% mutate(eqtlgen_egenes = str_split(eqtlgen_egenes, ",|;"),
                            gtex_egenes_spec = str_split(gtex_egenes_spec, ",|;"),
                            hichip_egene = str_split(hichip_egene, ",|;"),
                            genes_within_10kb = str_split(genes_within_10kb, ",|;"),
                            disease = str_split(disease, ",|;")) %>%
  unnest(eqtlgen_egenes) %>%
  unnest(gtex_egenes_spec) %>%
  unnest(hichip_egene) %>%
  unnest(genes_within_10kb) %>%
  unnest(disease)

egenes <- dplyr::filter(egenes, !is.na(hit_spec))
egenes <- pivot_longer(egenes,cols=c(eqtlgen_egenes, gtex_egenes_spec,hichip_egene,genes_within_10kb), 
                       names_to = "data_source", values_to = "egene")
egenes <- dplyr::filter(egenes, !is.na(egene))
egenes <- dplyr::select(egenes, hit_spec, egene)
colnames(egenes) <- c("disease", "gene")
egenes$source <- "MPRA"
egenes <- egenes %>% mutate(disease = str_split(disease, ",")) %>%
  unnest(disease)
```

```{r}
egene_hcs <- left_join(hcs,egenes, by=c("Gene" = "gene")) %>% distinct()
egene_hcs <- dplyr::filter(egene_hcs, !is.na(disease))
```

Make a table of hcs genes
```{r}
egenes_forhcs <- res_merge %>% dplyr::select( disease, hit_spec, Causal_SNP, eqtlgen_egenes, gtex_egenes_spec,hichip_egene,
                                       genes_within_10kb)
egenes_forhcs <- egenes_forhcs %>% mutate(eqtlgen_egenes = str_split(eqtlgen_egenes, ",|;"),
                            gtex_egenes_spec = str_split(gtex_egenes_spec, ",|;"),
                            hichip_egene = str_split(hichip_egene, ",|;"),
                            genes_within_10kb = str_split(genes_within_10kb, ",|;"),
                            disease = str_split(disease, ",|;")) %>%
  unnest(eqtlgen_egenes) %>%
  unnest(gtex_egenes_spec) %>%
  unnest(hichip_egene) %>%
  unnest(genes_within_10kb) %>%
  unnest(disease)

egenes_forhcs <- dplyr::filter(egenes_forhcs, !is.na(hit_spec))

egenes_forhcs <- pivot_longer(egenes_forhcs,cols=c(eqtlgen_egenes, gtex_egenes_spec,hichip_egene,genes_within_10kb), 
                       names_to = "data_source", values_to = "egene")
egenes_forhcs <- dplyr::filter(egenes_forhcs, !is.na(egene))
egenes_forhcs <- egenes_forhcs %>%
  dplyr::filter(egene %in% hcs$Gene) %>%
  distinct()
egenes_forhcs_grp <- egenes_forhcs %>% group_by(egene) %>%
  summarise(SNP = paste(sort(unique(Causal_SNP)), collapse=","),
            cancer = paste(sort(unique(hit_spec)), collapse= ","),
            data_source = paste(sort(unique(data_source)), collapse=","))

# write_tsv(egenes_forhcs_grp, "~/Documents/MPRA/Cancer_MPRA_Scaleup/MakingFigures/Mutated-HCS-genetable/hcs_minitable.txt")

```



```{r}
colnames(egene_hcs)
colnames(yesorno_df)
hcs_egenes <- egene_hcs
yesorno_df <- dplyr::select(yesorno_df, -snps)
egene_hcs <- dplyr::select(egene_hcs, -source)
yesorno_df$Cancer <- yesorno_df$celltype
yesorno_df$source <- "mutated"
egene_hcs$source <- "hcs"
colnames(yesorno_df) <- c("Gene", "disease", "Cancer", "source")

egene_both <- rbind(yesorno_df, egene_hcs)
```

```{r}
ggplot(egene_both, aes(x=disease, y = Cancer, label=Gene, col=source))+
#   geom_text(vjust = c(0,-1.2,0,1.2,0,1.2, 0,0,0,0,0,0,0,0,0,0,0,0,0,0,0))+
  geom_text() +
  theme(panel.background = element_rect(fill="white"),
        panel.grid.major = element_line(colour="grey94"))
egene_both$Gene
#egene_both$Gene
#MAP3K1,PIK3R1,HIST1H3B
#CMKLR1,GPC5
```

```{r}
cosmic <- read_tsv("~/Documents/MPRA/Cancer_MPRA_Scaleup/eGeneFiles/COSMIC/cmc_export.v92/cmc_export.tsv",
                   col_types =paste(rep("c", 57), collapse=""))
cosmic <- dplyr::filter(cosmic, GENE_NAME %in% egenes$gene)
colnames(cosmic)
cosmic <- cosmic[c(1, 3,4,16,17,24, 25,57)]
cosmic <- distinct(cosmic)
length(unique(cosmic$GENE_NAME))
unique(cosmic$CGC_TIER)
cosmic <- dplyr::filter(cosmic, !is.na(CGC_TIER))
```

```{r}
cosmic_dis <- cosmic %>% mutate(DISEASE = str_split(DISEASE, ";")) %>%
  unnest(DISEASE)
cosmic_dis <- cosmic_dis %>% mutate(Cancer = case_when(
  grepl("endometr", DISEASE) | grepl("endometr", WGS_DISEASE) ~ "endo",
  grepl("lung", DISEASE) | grepl("lung", WGS_DISEASE) ~ "airway",
  grepl("pros", DISEASE) | grepl("pros", WGS_DISEASE) ~ "pros",
  grepl("kidney", DISEASE) | grepl("kidney", WGS_DISEASE) ~ "renal",
  grepl("ovar", DISEASE) | grepl("ovar", WGS_DISEASE) ~ "ov",
  grepl("lymph", DISEASE) | grepl("lymph", WGS_DISEASE) ~ "gm",
  grepl("panc", DISEASE) | grepl("panc", WGS_DISEASE) ~ "panc",
  grepl("breast", DISEASE) | grepl("breast", WGS_DISEASE) ~ "hmec",
  grepl("esoph", DISEASE) | grepl("esoph", WGS_DISEASE) ~ "eso",
  grepl("melanoma", DISEASE) | grepl("melanoma", WGS_DISEASE) ~ "mc",
  grepl("large_intestine", DISEASE) | grepl("large_intestine", WGS_DISEASE) ~ "colon",
  grepl("thyroid", DISEASE) | grepl("thyroid", WGS_DISEASE) ~ "thy",
  grepl("glioma", DISEASE) | grepl("glioma", WGS_DISEASE) ~ "ast",
))

colnames(cosmic)
cosmic_cut <- dplyr::select(cosmic_dis, GENE_NAME, Cancer)
cosmic_cut <- distinct(cosmic_cut)
cosmic_cut <- left_join(cosmic_cut, dplyr::select(egenes, disease, gene),
                        by=c("GENE_NAME"="gene"))
cosmic_cut <- cosmic_cut %>% distinct() %>%
  dplyr::filter(!is.na(Cancer))
```


```{r}
cosmic_cut$source <- "COSMIC"
colnames(egene_both)
colnames(cosmic_cut)
colnames(cosmic_cut)[1] <- "Gene"
egene_three <- rbind(egene_both, cosmic_cut)
egene_three <- distinct(egene_three)
```

```{r}
install.packages("ggrepel")
library(ggrepel)

ggplot(egene_three, aes(x=disease, y = Cancer, label=Gene, col=source))+
  geom_text(size=2.5, position = position_jitter())+
  theme(panel.background = element_rect(fill="white"),
        panel.grid.major = element_line(colour="grey94"))
egene_three$Gene
2 - MAP3K1
3 - PIK3R1
4 - HIST1H3B

5 CMKLR1
6 - GPC5

9 - NKX3-1 (with RAD51B)
12 - CDKN2A
13 - CDKN2A
21 - TCF7L2
27 - BUB1B
28 - HIST1H3B
29 - HIST1H3B
34 - PIK3R1
35 - PIK3R1
36 - PIK3R1

```
```{r}
egene_three <- egene_three %>% mutate(`SNP cancer type` = case_when(
  disease == "airway" ~ "LUAD",
  disease == "ast" ~ "GBM",
  disease == "endo" ~ "UCEC",
  disease == "eso" ~ "ESCA",
  disease == "gm" ~ "DLBC",
  disease == "hmec" ~ "BRCA",
  disease == "mc" ~ "SKCM",
  disease == "pros" ~ "PRAD",
  disease == "thy" ~ "THCA",
  disease == "kc" ~ "KC",
  disease == "colon" ~ "COAD",
  disease == "ov" ~ "OVCA",
  disease == "panc" ~ "PAAD",
))
egene_three <- egene_three %>% mutate(`Gene mutation cancer type` = case_when(
  Cancer == "airway" ~ "LUAD",
  Cancer == "ast" ~ "GBM",
  Cancer == "endo" ~ "UCEC",
  Cancer == "eso" ~ "ESCA",
  Cancer == "gm" ~ "DLBC",
  Cancer == "hmec" ~ "BRCA",
  Cancer == "mc" ~ "SKCM",
  Cancer == "pros" ~ "PRAD",
  Cancer == "thy" ~ "THCA",
  Cancer == "kc" ~ "KC",
  Cancer == "colon" ~ "COAD",
  Cancer == "ov" ~ "OVCA",
  Cancer == "panc" ~ "PAAD",
  Cancer == "renal" ~ "KIRC"
))
ggplot(dplyr::filter(egene_three, !source == "mutated"), aes(x=`SNP cancer type`, 
                                                             y = `Gene mutation cancer type`, label=Gene,
                                                             col=source)) +
  geom_text_repel(size=2.5)+
  theme(panel.background = element_rect(fill="white"),
        panel.grid.major = element_line(colour="grey94"))
```
Add coding snps
Digression to get coding SNPs and all_egenes df, copy pasted from AddingCodingSNPs:
```{r}
all_snps <- read_tsv("~/Documents/MPRA/Cancer_MPRA_Scaleup/LibraryFiles/YZ_SNP_Files/cancer/all-causal-SNP-16cancers.txt",
                     col_types="ccccccccccccccccccccccccccc")
coding_snps <- dplyr::filter(all_snps, grepl("exonic", Func.refGene)) %>%
  dplyr::select(Disease, Gene.refGene) %>%
  dplyr::filter(!Disease == "bladder") %>% distinct()
coding_snps <- coding_snps %>% mutate(Disease = case_when(
  Disease == "brca" ~ "hmec",
  Disease == "endometrial" ~ "endo",
  Disease == "esophagus" ~ "eso",
  Disease == "kidney" ~ "renal",
  Disease == "lung" ~ "airway",
  Disease == "lymphoma" ~ "gm",
  Disease == "melanoma" ~ "mc",
  Disease == "ovca" ~ "ov",
  Disease == "paad" ~ "panc",
  Disease == "prad" ~ "pros",
  Disease == "skin" ~ "kc",
  Disease == "thyroid" ~ "thy",
  T ~ Disease
))
colnames(coding_snps) <- c("disease", "gene")
coding_snps$source <- "coding_snp"

hcs <- read_tsv("~/Documents/MPRA/Cancer_MPRA_Scaleup/CodingSNPs/HereditaryCancerSyndromes.txt")
hcs <- hcs %>% mutate(Cancer = str_split(Cancer, ",")) %>%
  unnest(Cancer)
hcs <- dplyr::select(hcs, Cancer, Gene)
colnames(hcs)  <- c("disease", "gene")
hcs$source <- "hereditary_cancer_syndrome"


res_merge <- read_tsv("~/Documents/MPRA/Cancer_MPRA_Scaleup/Analysis11.12.20/Analysis11.27.20/res_merge_withhitannot_031021.tsv")
egenes <- res_merge %>% dplyr::select( disease, hit_spec, eqtlgen_egenes, gtex_egenes_spec,hichip_egene,
                                       genes_within_10kb)
egenes <- egenes %>% mutate(eqtlgen_egenes = str_split(eqtlgen_egenes, ",|;"),
                            gtex_egenes_spec = str_split(gtex_egenes_spec, ",|;"),
                            hichip_egene = str_split(hichip_egene, ",|;"),
                            genes_within_10kb = str_split(genes_within_10kb, ",|;"),
                            disease = str_split(disease, ",|;")) %>%
  unnest(eqtlgen_egenes) %>%
  unnest(gtex_egenes_spec) %>%
  unnest(hichip_egene) %>%
  unnest(genes_within_10kb) %>%
  unnest(disease)

egenes_with_nonhits <- egenes

egenes <- dplyr::filter(egenes, !is.na(hit_spec))
egenes <- pivot_longer(egenes,cols=c(eqtlgen_egenes, gtex_egenes_spec,hichip_egene,genes_within_10kb), 
                       names_to = "data_source", values_to = "egene")
egenes <- dplyr::filter(egenes, !is.na(egene))
egenes <- dplyr::select(egenes, hit_spec, egene)
colnames(egenes) <- c("disease", "gene")
egenes$source <- "MPRA"
egenes <- egenes %>% mutate(disease = str_split(disease, ",")) %>%
  unnest(disease)

all_egenes <- rbind(egenes, coding_snps)
all_egenes <- rbind(all_egenes, hcs)
all_egenes <- distinct(all_egenes)
table(all_egenes$disease)


all_egenes <- all_egenes %>% mutate(gene_convert = case_when(
  gene == "H1-5" ~ "HIST1H1B",
  gene == "H2AC13" ~ "HIST1H2AI",
  gene == "H2AC14" ~ "HIST1H2AJ",
  gene == "H2AC15" ~ "HIST1H2AK",
  gene == "H2AC16" ~ "HIST1H2AL",
  gene == "H2AC17" ~ "HIST1H2AM",
  gene == "H2BC13" ~ "HIST1H2BL",
  gene == "H2BC14" ~ "HIST1H2BM",
  gene == "H2BC15" ~ "HIST1H2BN",
  gene == "H2BC17" ~ "HIST1H2BO",
  gene == "H3C10" ~ "HIST1H3H",
  gene == "H3C11" ~ "HIST1H3I",
  gene == "H3C12" ~ "HIST1H3J",
  gene == "H4C12" ~ "HIST1H4K",
  gene == "H4C13" ~ "HIST1H4L",
  gene == "H3C12" ~ "HIST1H3J",
  T ~ gene))
```








```{r}
# just need to add cosmic
cosmic_all <- read_tsv("~/Documents/MPRA/Cancer_MPRA_Scaleup/eGeneFiles/COSMIC/cmc_export.v92/cmc_export.tsv",
                   col_types =paste(rep("c", 57), collapse=""))
cosmic_all <- dplyr::filter(cosmic_all, !is.na(CGC_TIER))
cosmic_all_dis <- cosmic_all %>% mutate(DISEASE = str_split(DISEASE, ";")) %>%
  unnest(DISEASE)
cosmic_dis <- cosmic_dis %>% mutate(Cancer = case_when(
  grepl("endometr", DISEASE) | grepl("endometr", WGS_DISEASE) ~ "endo",
  grepl("lung", DISEASE) | grepl("lung", WGS_DISEASE) ~ "airway",
  grepl("pros", DISEASE) | grepl("pros", WGS_DISEASE) ~ "pros",
  grepl("kidney", DISEASE) | grepl("kidney", WGS_DISEASE) ~ "renal",
  grepl("ovar", DISEASE) | grepl("ovar", WGS_DISEASE) ~ "ov",
  grepl("lymph", DISEASE) | grepl("lymph", WGS_DISEASE) ~ "gm",
  grepl("panc", DISEASE) | grepl("panc", WGS_DISEASE) ~ "panc",
  grepl("breast", DISEASE) | grepl("breast", WGS_DISEASE) ~ "hmec",
  grepl("esoph", DISEASE) | grepl("esoph", WGS_DISEASE) ~ "eso",
  grepl("melanoma", DISEASE) | grepl("melanoma", WGS_DISEASE) ~ "mc",
  grepl("large_intestine", DISEASE) | grepl("large_intestine", WGS_DISEASE) ~ "colon",
  grepl("thyroid", DISEASE) | grepl("thyroid", WGS_DISEASE) ~ "thy",
  grepl("glioma", DISEASE) | grepl("glioma", WGS_DISEASE) ~ "ast",
))

cosmic_format <- dplyr::select(cosmic_all, DISEASE, GENE_NAME) %>%
  distinct()
colnames(cosmic_format) <- c("disease", "gene")
cosmic_format <- cosmic_format %>% mutate(gene_convert = gene,
                                          source = "cosmic")
all_egenes <- rbind(all_egenes, cosmic_format)



```

Write out the files to use in BioVenn
```{r}
write(all_egenes$gene[all_egenes$source == "MPRA"], "BioVenn/mpra_egenes")
write(all_egenes$gene[all_egenes$source == "cosmic"], "BioVenn/cosmic_genes")
write(all_egenes$gene[all_egenes$source == "coding_snp"], "BioVenn/coding_snp_genes")
write(all_egenes$gene[all_egenes$source == "hereditary_cancer_syndrome"], "BioVenn/hereditary_cancer_syndrome_genes")


```





Make an Euler plot
```{r}
euler_df <- all_egenes %>% dplyr::select(gene_convert, source) %>%
  distinct() %>%
  group_by(gene_convert) %>%
  summarise(source = paste(unique(source), collapse=","))

euler_df <- euler_df %>%
  mutate(coding = ifelse(grepl("coding_snp", source), 1, 0),
         hcs = ifelse(grepl("hereditary", source), 1, 0),
         mpra = ifelse(grepl("MPRA", source), 1, 0),
         cosmic = ifelse(grepl("cosmic", source), 1, 0))
         
                              
library(eulerr)
euler(euler_df[,3:6])
postscript(file="venndiagram_codingmpracosmic.ps")
plot(euler(euler_df[,c(3,5,6)],shape="ellipse"), legend = list(side = "right"))
dev.off()

```


